name: imaris_dev

channels:
  - defaults
dependencies:
  - python=3.7.0 #Python version supported by imaris
  - pip
  - pip:
    - SimpleITK == 2.2.1 #last SimpleITK version providing Python 3.7 binaries
    - numpy
    - pandas
    - h5py>=2.10.0
    - PySide6
    - openpyxl
    - docutils   #used for converting rst to html (see help_dialog.py)
    - pygments   #used for code highlighting (see help_dialog.py)
    - qdarkstyle #dark stylesheet for Qt applications
    - matplotlib
    - sitkibex #sitk-ibex registration
    - pytest #only used for development, testing
    - flake8 #only used for development, test code formatting
    - black #only used for development, code formatting
    - pre-commit #only used for development, multi-language pre commit hooks
