name: Imaris Extension Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # linting and checking for secrets is only done once
  # no need for multi platform/Python versions.
  preliminary_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
    - name: Lint with flake8
      run: |
        python -m flake8 . --show-source --statistics
    # run trufflehog3 with no-entropy because our testing code
    # uses md5 hashes which are all high entropy
    - name: Install and run trufflehog3 secrets scanner
      run: |
        python -m pip install trufflehog3
        trufflehog3 -v --no-entropy . && echo "tufflehog3 secrets scan passed"

  test:
    # only run the code testing if linting and secrets passed
    needs: preliminary_test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Create LFS file list
      run: |
        git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
    - name: Restore LFS cache
      uses: actions/cache@v3
      id: lfs-cache
      with:
        path: .git/lfs
        key: lfs-v1-${{ hashFiles('.lfs-assets-id') }}
        restore-keys:
          lfs-v1-       
    - name: Git LFS Pull
      run: |
        git lfs pull
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Test with pytest
      run: |
        python -m pytest

  documentation:
    # only run if this workflow was triggered by a push event on main branch
    # either direct push to main or a merged pull request which also generates
    # a push event.
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Install pandoc
      run: |
        sudo apt-get install pandoc
    - name: Update documentation
      run: |
        python docs/generate_documentation.py
        git checkout -b gh-pages origin/gh-pages
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        mv -f docs/*.html .
        git add *.html
        git commit --amend --no-edit
        git push origin gh-pages --force
